/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AltJ */

#ifndef _Included_AltJ
#define _Included_AltJ
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AltJ
 * Method:    cFunctionName
 * Signature: ([CIII)[I
 */
JNIEXPORT jintArray JNICALL Java_AltJ_cFunctionName
  (JNIEnv *, jobject, jcharArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
